_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${paths.output_dir}

deterministic: False

accelerator: cpu
devices: 1
strategy:
  _target_: lightning.pytorch.strategies.SingleDeviceStrategy
  device: cpu
num_nodes: 1
min_epochs: 1
max_steps: 100
precision: 32
val_check_interval: 50
check_val_every_n_epoch: null
num_sanity_val_steps: 0
limit_val_batches: 0.0
